version: '3.4'

services:
  extractor:
    dns: 8.8.8.8
    image: community.docker.edu-sharing.com/oeh-search-meta:latest
    ports:
      - "5057:5057"
    links:
      - splash
      - accessibility
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5057/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
  splash:
    dns: 8.8.8.8
    image: scrapinghub/splash:master
    command: --maxrss 4000
    restart: always
    ports:
      - "8050:8050"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8050/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
  accessibility:
    dns: 8.8.8.8
    image: community.docker.edu-sharing.com/oeh-search-meta_lighthouse:latest
    restart: always
    ports:
      - "5058:5058"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5058/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
  db:
      image: postgres
      container_name: oeh-search-meta_db_volume
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=storage
      volumes:
        - db_volume:/var/lib/mysql
      networks:
        - backend

volumes:
  db_volume:

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450